In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
import xgboost as xgb
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv('/content/Spotify Tracks Dataset dataset.csv')

In [3]:
df.head()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [4]:
df['track_genre'].unique()

array(['acoustic', 'afrobeat', 'alt-rock', 'alternative', 'ambient',
       'anime', 'black-metal', 'bluegrass', 'blues', 'brazil',
       'breakbeat', 'british', 'cantopop', 'chicago-house', 'children',
       'chill', 'classical', 'club', 'comedy', 'country', 'dance',
       'dancehall', 'death-metal', 'deep-house', 'detroit-techno',
       'disco', 'disney', 'drum-and-bass', 'dub', 'dubstep', 'edm',
       'electro', 'electronic', 'emo', 'folk', 'forro', 'french', 'funk',
       'garage', 'german', 'gospel', 'goth', 'grindcore', 'groove',
       'grunge', 'guitar', 'happy', 'hard-rock', 'hardcore', 'hardstyle',
       'heavy-metal', 'hip-hop', 'honky-tonk', 'house', 'idm', 'indian',
       'indie-pop', 'indie', 'industrial', 'iranian', 'j-dance', 'j-idol',
       'j-pop', 'j-rock', 'jazz', 'k-pop', 'kids', 'latin', 'latino',
       'malay', 'mandopop', 'metal', 'metalcore', 'minimal-techno', 'mpb',
       'new-age', 'opera', 'pagode', 'party', 'piano', 'pop-film', 'pop',
       'power-pop', 'progressive-house', 'psych-rock', 'punk-rock',
       'punk', 'r-n-b', 'reggae', 'reggaeton', 'rock-n-roll', 'rock',
       'rockabilly', 'romance', 'sad', 'salsa', 'samba', 'sertanejo',
       'show-tunes', 'singer-songwriter', 'ska', 'sleep', 'songwriter',
       'soul', 'spanish', 'study', 'swedish', 'synth-pop', 'tango',
       'techno', 'trance', 'trip-hop', 'turkish', 'world-music'],
      dtype=object)

In [5]:
df = df[
    df['track_genre'].isin(
        ['club', 'pop', 'brazil', 'blues', 'brazil', 'british']
    )
    ]

In [6]:
df.head()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
8000,8000,5MAK1nd8R6PWnle1Q1WJvh,Everybody Loves an Outlaw,I See Red,I See Red,77,230613,False,0.509,0.448,...,-7.552,0,0.0357,0.00713,0.013700,0.2440,0.221,156.909,3,blues
8001,8001,2tznHmp70DxMyr2XhWLOW0,Cage The Elephant,Melophobia,Cigarette Daydreams,79,208760,False,0.636,0.676,...,-3.442,1,0.0263,0.08070,0.000000,0.0831,0.273,113.980,4,blues
8002,8002,7vguMCv8uVuZLiQJ156u3Z,Sam Tinnesz;Yacht Money,Play with Fire (feat. Yacht Money),Play with Fire (feat. Yacht Money),76,180690,False,0.573,0.539,...,-6.091,0,0.0322,0.01620,0.000012,0.1050,0.390,75.012,4,blues
8003,8003,3dPQuX8Gs42Y7b454ybpMR,The White Stripes,Elephant,Seven Nation Army,84,232106,False,0.743,0.446,...,-7.807,0,0.0683,0.00390,0.118000,0.3370,0.278,123.596,4,blues
8004,8004,6zC0mpGYwbNTpk9SKwh08f,Eric Clapton,Slowhand 35th Anniversary (Super Deluxe),Wonderful Tonight,76,225026,False,0.572,0.214,...,-15.625,1,0.0293,0.64900,0.129000,0.1250,0.485,95.542,4,blues

In [7]:
df.drop(
    columns=[
        'Unnamed: 0',
        'track_id',
        'track_name',
        'artists',
        'album_name',
        'time_signature'
    ],
    axis=1,
    inplace = True
)

In [8]:
df.head()

,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,track_genre
8000,77,230613,False,0.509,0.448,4,-7.552,0,0.0357,0.00713,0.013700,0.2440,0.221,156.909,blues
8001,79,208760,False,0.636,0.676,2,-3.442,1,0.0263,0.08070,0.000000,0.0831,0.273,113.980,blues
8002,76,180690,False,0.573,0.539,2,-6.091,0,0.0322,0.01620,0.000012,0.1050,0.390,75.012,blues
8003,84,232106,False,0.743,0.446,4,-7.807,0,0.0683,0.00390,0.118000,0.3370,0.278,123.596,blues
8004,76,225026,False,0.572,0.214,7,-15.625,1,0.0293,0.64900,0.129000,0.1250,0.485,95.542,blues

In [9]:
print(df.isnull().sum())

popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
track_genre         0
dtype: int64

In [10]:
df.dropna(inplace=True)

In [11]:
x = df.drop('track_genre', axis=1)
y = df['track_genre']

In [12]:
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=0.2, random_state=42)

Label output

In [13]:
label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train)
y_val = label_encoder.transform(y_val)

Scaling features

In [14]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_val = scaler.transform(x_val)

**Model**

In [15]:
xgb_classifier = xgb.XGBClassifier(
    random_state=42
)

xgb_classifier.fit(x_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [16]:
y_pred = xgb_classifier.predict(x_val)

In [17]:
val_accuracy = accuracy_score(y_val, y_pred)
print(f"Validation Accuracy: {val_accuracy: .4f}")

Validation Accuracy:  0.7550

In [18]:
print(classification_report(y_val, y_pred))

              precision    recall  f1-score   support

           0       0.67      0.65      0.66       216
           1       0.83      0.81      0.82       190
           2       0.61      0.56      0.59       192
           3       0.83      0.82      0.82       210
           4       0.82      0.94      0.87       192

    accuracy                           0.76      1000
   macro avg       0.75      0.76      0.75      1000
weighted avg       0.75      0.76      0.75      1000

In [19]:
print(confusion_matrix(y_val, y_pred))

[[140   5  43  13  15]
 [  9 154   9  13   5]
 [ 49   6 108   8  21]
 [  6  20  12 172   0]
 [  5   0   5   1 181]]

Hyperparameter tuning

In [55]:
param_grid = {
    'n_estimators':[100, 200, 300, 400],
    'learning_rate':[0.01, 0.1, 0.2],
    'max_depth':[3, 6, 9],
    'min_child_weight':[1, 3, 5],
    'subsample':[0.7, 0.85, 1],
    'colsample_bytree':[0.7, 0.85, 1],
    'reg_alpha':[1, 3, 5],
    'reg_lambda':[1]
}
grid_search = RandomizedSearchCV(
    estimator=xgb.XGBClassifier(
        random_state=42,
        eval_metric='mlogloss'
    ),
    param_distributions=param_grid,
    cv=5,
    scoring='accuracy',
    n_iter=20,
    n_jobs=-1,
    random_state=42
)

In [56]:
grid_search.fit(x_train, y_train)
best_xgb = grid_search.best_estimator_
print('Best parameters:')
print(grid_search.best_params_)
print('\nBest cv score:', grid_search.best_score_)

Best parameters:
{'subsample': 0.7, 'reg_lambda': 1, 'reg_alpha': 3, 'n_estimators': 100, 'min_child_weight': 1, 'max_depth': 9, 'learning_rate': 0.1, 'colsample_bytree': 0.85}

Best cv score: 0.7755

In [61]:
y_pred = best_xgb.predict(x_val)

test_accuracy = accuracy_score(y_val, y_pred)

print("Test Accuracy:", test_accuracy)

print("\nClassification Report:")
print(classification_report(y_val, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_val, y_pred))

Test Accuracy: 0.763

Classification Report:
              precision    recall  f1-score   support

           0       0.72      0.68      0.70       216
           1       0.83      0.84      0.83       190
           2       0.60      0.55      0.57       192
           3       0.83      0.81      0.82       210
           4       0.81      0.95      0.88       192

    accuracy                           0.76      1000
   macro avg       0.76      0.76      0.76      1000
weighted avg       0.76      0.76      0.76      1000


Confusion Matrix:
[[146   3  43  11  13]
 [  7 159  11   9   4]
 [ 41   7 106  14  24]
 [  4  22  13 170   1]
 [  5   0   5   0 182]]