In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [ ]:
df = pd.read_csv('/content/salaries(decision_tree).csv')

In [ ]:
df.head()

  company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [ ]:
features = df.drop('salary_more_then_100k',axis='columns')
target = df.salary_more_then_100k

In [ ]:
le_company = LabelEncoder()
le_job = LabelEncoder()
le_degree = LabelEncoder()

In [ ]:
features['company_n'] = le_company.fit_transform(features['company'])
features['job_n'] = le_job.fit_transform(features['job'])
features['degree_n'] = le_degree.fit_transform(features['degree'])

In [ ]:
features_n = features.drop(['company', 'job', 'degree'], axis='columns')

In [ ]:
features_n.head()

   company_n  job_n  degree_n
0          2      2         0
1          2      2         1
2          2      0         0
3          2      0         1
4          2      1         0

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(features_n, target, test_size=0.2, random_state = 2)

In [ ]:
model = DecisionTreeClassifier()
model.fit(X_train, Y_train)
Y_predict = model.predict(X_test)
result = accuracy_score(Y_test, Y_predict)
print(result * 100, '%')

75.0 %

In [ ]:
company = "google"
job = "computer programmer"
degree = "bachelors"

company_n = le_company.transform([company])[0]
job_n = le_job.transform([job])[0]
degree_n = le_degree.transform([degree])[0]

result = model.predict([[company_n, job_n, degree_n]])
if result[0] == 1:
    print("Salary > 100k ✅")
else:
    print("Salary <= 100k ❌")

Salary > 100k ✅

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(